spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skypro_ads
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true
    url: jdbc:postgresql://localhost:5432/skypro_ads
    user: username
    password: password
path:
  dir:
    image: /app/images/
springdoc:
  api-docs:
    enabled: true