-- liquibase formatted sql
-- changeset EAKok:001
CREATE TABLE user_entities (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) UNIQUE CHECK (LENGTH(TRIM(username)) >= 4 AND username ~ '^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(16) NOT NULL CHECK (LENGTH(TRIM(first_name)) >= 2),
    last_name VARCHAR(16) NOT NULL CHECK (LENGTH(TRIM(last_name)) >= 2),
    phone VARCHAR(16) NOT NULL CHECK (phone ~ '^\+7\s?\(?[0-9]{3}\)?\s?[0-9]{3}-?[0-9]{2}-?[0-9]{2}$'),
    authority VARCHAR(10) NOT NULL CHECK (authority IN ('ROLE_USER', 'ROLE_ADMIN')),
    image VARCHAR(255)
);