-- liquibase formatted sql
-- changeset EAKok:002
CREATE TABLE ad_entities (
    pk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(32) NOT NULL CHECK (LENGTH(TRIM(title)) >= 4),
    description VARCHAR(64) NOT NULL CHECK (LENGTH(TRIM(description)) >= 8),
    price INTEGER NOT NULL CHECK (price >= 0 AND price <= 10000000),
    image VARCHAR(255) NOT NULL,
    author INT NOT NULL,
    FOREIGN KEY (author) REFERENCES user_entities(id)
);