-- liquibase formatted sql
-- changeset EAKok:003
CREATE TABLE comment_entities (
    pk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(64) NOT NULL CHECK (LENGTH(TRIM(text)) >= 8),
    created_at BIGINT NOT NULL,
    author INT NOT NULL,
    ad_entity INT NOT NULL,
    FOREIGN KEY (author) REFERENCES user_entities(id),
    FOREIGN KEY (ad_entity) REFERENCES ad_entities(pk)
);